// app/components/color-mode-button.vue
<script setup lang="ts">
import { UButton } from "#components";

const colorMode = useColorMode();

function toggleColorMode(e: MouseEvent | PointerEvent | KeyboardEvent) {
  if (import.meta.server)
    return;

  // Flip immediately if user prefers reduced motion
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
    colorMode.preference = colorMode.value === "dark" ? "light" : "dark";
    return;
  }

  // Safely detect support (don’t detach the method)
  const hasVT = typeof (document as any).startViewTransition === "function";

  // Determine click position; fall back to center for keyboard triggers
  let x = window.innerWidth / 2;
  let y = window.innerHeight / 2;
  if ("clientX" in e && typeof e.clientX === "number") {
    x = e.clientX;
    y = e.clientY;
  }

  const next = colorMode.value === "dark" ? "light" : "dark";

  if (!hasVT) {
    // No View Transitions support → just toggle
    colorMode.preference = next;
    return;
  }

  // Compute circle radius
  const endRadius = Math.hypot(
    Math.max(x, window.innerWidth - x),
    Math.max(y, window.innerHeight - y),
  );

  // Set CSS vars for the keyframes
  const root = document.documentElement;
  root.style.setProperty("--circle-x", `${x}px`);
  root.style.setProperty("--circle-y", `${y}px`);
  root.style.setProperty("--circle-radius", `${endRadius}px`)

  // IMPORTANT: call with `document` bound
  ;(document as any).startViewTransition.call(document, () => {
    colorMode.preference = next;
  });
}
</script>

<template>
  <ClientOnly>
    <UButton
      size="sm"
      color="neutral"
      variant="ghost"
      :icon="colorMode.value === 'dark' ? 'i-lucide-sun' : 'i-lucide-moon'"
      aria-label="Toggle color mode"
      :aria-pressed="colorMode.value === 'dark'"
      class="rounded-full"
      @click="toggleColorMode"
      @keyup.enter="toggleColorMode"
      @keyup.space.prevent="toggleColorMode"
    />
  </ClientOnly>
</template>

// src/components/color-mode-button.tsx
import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

function readDarkMode() {
  return document.documentElement.classList.contains("dark");
}

export function ColorModeButton() {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    setDark(readDarkMode());
  }, []);

  function applyMode(nextDark: boolean) {
    document.documentElement.classList.toggle("dark", nextDark);
    localStorage.setItem("portfolio:color-mode", nextDark ? "dark" : "light");
    setDark(nextDark);
  }

  function toggleColorMode(event: React.MouseEvent<HTMLButtonElement>) {
    const nextDark = !readDarkMode();

    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      applyMode(nextDark);
      return;
    }

    const startViewTransition = document.startViewTransition?.bind(document);

    if (!startViewTransition) {
      applyMode(nextDark);
      return;
    }

    const x = event.clientX || window.innerWidth / 2;
    const y = event.clientY || window.innerHeight / 2;
    const endRadius = Math.hypot(
      Math.max(x, window.innerWidth - x),
      Math.max(y, window.innerHeight - y),
    );

    document.documentElement.style.setProperty("--circle-x", `${x}px`);
    document.documentElement.style.setProperty("--circle-y", `${y}px`);
    document.documentElement.style.setProperty("--circle-radius", `${endRadius}px`);

    startViewTransition(() => {
      applyMode(nextDark);
    });
  }

  return (
    <button
      aria-label="Toggle color mode"
      aria-pressed={dark}
      className="inline-flex h-9 w-9 items-center justify-center rounded-full text-neutral-600 transition hover:bg-neutral-200/70 hover:text-neutral-950 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:hover:text-white"
      onClick={toggleColorMode}
      type="button"
    >
      {dark ? <Sun aria-hidden="true" size={17} /> : <Moon aria-hidden="true" size={17} />}
    </button>
  );
}
